### ISSUE TITLE
CPress Review Team Report - results

### ISSUE THREAD

**Issue by tradesouthwest** [luthemes/amicable#1]
7 files with erros

1.
FILE: /var/www/html/cp-plugin-review/amicable/public/views/header/default.php

FOUND 1 ERROR AFFECTING 1 LINE

 34 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterOpen)

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

2.
FILE: /var/www/html/cp-plugin-review/amicable/public/views/comment/default.php

FOUND 4 ERRORS AFFECTING 4 LINES

  4 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterOpen)
  6 | ERROR | [x] Multi-line array item not aligned correctly; expected 4
    |       |     spaces, but found 12
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 12 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterOpen)
 16 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterOpen)

PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY

3.
FILE: /var/www/html/cp-plugin-review/amicable/public/views/menu/social.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 1 | WARNING | No PHP code was found in this file and short open tags are not
   |         | allowed by this install of PHP. This file may be using short
   |         | open tags but PHP does not allow them.
   |         | (Internal.NoCodeFound)

5.
FILE: /var/www/html/cp-plugin-review/amicable/public/views/menu/primary.php

FOUND 1 ERROR AFFECTING 1 LINE

 18 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterOpen)

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

6.
FILE: /var/www/html/cp-plugin-review/amicable/config/image-sizes.php

FOUND 9 ERRORS AFFECTING 9 LINES

 17 | ERROR | [x] Multi-line array item not aligned correctly; expected 5
    |       |     spaces, but found 4
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 24 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 29 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 34 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 39 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 45 | ERROR | [x] Multi-line array item not aligned correctly; expected 5
    |       |     spaces, but found 4
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 52 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 58 | ERROR | [x] Multi-line array item not aligned correctly; expected 5
    |       |     spaces, but found 4
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)
 65 | ERROR | [x] Multi-line array item not aligned correctly; expected 9
    |       |     spaces, but found 8
    |       |     (WordPress.Arrays.ArrayIndentation.MultiLineArrayItemNotAligned)

PHPCBF CAN FIX THE 9 MARKED SNIFF VIOLATIONS AUTOMATICALLY

7.
FILE: /var/www/html/cp-plugin-review/amicable/app/functions-template.php

FOUND 1 ERROR AFFECTING 1 LINE

 31 | ERROR | Using short ternaries is not allowed
    |       | (WordPress.PHP.DisallowShortTernary.Found)

**Comment by techkodeninja** [comment]
are u sure these are warnings/errors. i do not see these when i run cpcs.
